drop table scotty.COUNTRIES CASCADE CONSTRAINTS ;
drop table scotty.DEPARTMENTS CASCADE CONSTRAINTS ;
drop table scotty.EMPLOYEES CASCADE CONSTRAINTS ;
drop table scotty.JOBS CASCADE CONSTRAINTS ;
drop table scotty.JOB_HISTORY CASCADE CONSTRAINTS ;
drop table scotty.LOCATIONS CASCADE CONSTRAINTS ;
drop table scotty.REGIONS CASCADE CONSTRAINTS ;
exit
